name: Bitrise-PR-comment

on: issue_comment
jobs:
  pr_commented:
    # This job only runs for pull request comments
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR informations
        id: pr_data
        run: |
          echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
      - name: PR comment
        run: |
          COMMENT="${{ github.event.comment.body }}"
          
          WORKFLOW = ""
          if [ "$COMMENT" = "run tests" ]; then
            WORKFLOW="pr-jobs" 
          elif [ "$COMMENT" = "make app" ]; then
            WORKFLOW="build-app"
          elif [ "$COMMENT" = "unit test" ]; then
            WORKFLOW="unit-test"
          fi
          
          # skip curl if workflow didn't match
          if [ "$WORKFLOW" = "" ]; then
            echo "Workflow not found"
            exit 1
          fi
          
          
          BRANCH=${{ steps.pr_data.outputs.branch }}"
          APP_SLUG=${{ secrets.BITRISE_APP_SLUG }}
          BUILD_TRIGGER_TOKEN=${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          curl https://app.bitrise.io/app/$APP_SLUG/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"'${BUILD_TRIGGER_TOKEN}'"}, "build_params":{"branch":"'${BRANCH}'","workflow_id":"'${WORKFLOW}'"},"triggered_by":"curl"}'
