name: Bitrise-CI

on:
  pull_request_review_comment:
    types: [created]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      workflow:
        description: 'Workflow name'
        required: true
        default: 'pr-jobs'

jobs:
  manual_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          BRANCH=${{ github.event.inputs.branch }}
          WORKFLOW=${{ github.event.inputs.workflow }}
          curl https://app.bitrise.io/app/4c527551314ba218/build/start.json \
          --data '{"hook_info":{"type":"bitrise","build_trigger_token":"AfYFen-5OC3qNFFO23E8FA"}, "build_params":{"branch":"${BRANCH}","workflow_id":"${WORKFLOW}"},"triggered_by":"curl"}'  
  
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event }}
    
