name: Bitrise-Manual

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      workflow:
        description: 'Workflow name'
        required: true
        default: 'pr-jobs'

jobs:
  manual_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          BRANCH=${{ github.event.inputs.branch }}
          WORKFLOW=${{ github.event.inputs.workflow }}
          
          # add to the GITHUB ENV
          APP_SLUG=4c527551314ba218
          BUILD_TRIGGER_TOKEN=AfYFen-5OC3qNFFO23E8FA
          curl https://app.bitrise.io/app/$APP_SLUG/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"'${BUILD_TRIGGER_TOKEN}'"}, "build_params":{"branch":"'${BRANCH}'","workflow_id":"'${WORKFLOW}'"},"triggered_by":"curl"}'
