name: Bitrise-PR-comment

on: issue_comment
jobs:  
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
#     if: ${{ github.event.issue.pull_request }}
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR number ${{ github.event.issue.number }}"
          echo "PR Title ${{ github.event.issue.title }}"
          echo "Event ${{ github.event_name }}"
          echo "Comment ${{ github.event.comment.body }}"
          echo "Branch ${{ github.head_ref }}"    
          echo "GITHUB_SHA ${GITHUB_SHA}"
          echo "GITHUB_REF ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"
          
          
          # APP_SLUG=${{ secrets.BITRISE_APP_SLUG }}
          # BUILD_TRIGGER_TOKEN=${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          # curl https://app.bitrise.io/app/$APP_SLUG/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"'${BUILD_TRIGGER_TOKEN}'"}, "build_params":{"branch":"'${BRANCH}'","workflow_id":"'${WORKFLOW}'"},"triggered_by":"curl"}'
