name: Bitrise-PR-comment

on: issue_comment
jobs:
  pr_commented:
    # This job only runs for pull request comments
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: github-result
        with:
          script: |
            const result = await github.request("${{ github.event.issue.pull_request.url }}")
            return result.data.head
          result-encoding: json
      
      - name: Get result
        id: pr-result
        run: |
          echo "::set-output name=branch::${{fromJson(steps.github-result.outputs.result).ref}}"
          echo "::set-output name=sha::${{fromJson(steps.github-result.outputs.result).sha}}"

      - name: PR comment
        run: |
          COMMENT="${{ github.event.comment.body }}"
          
          COMMENT_LOWERCASE=${COMMENT,,}
          
          echo "orig ${COMMENT} new ${COMMENT_LOWERCASE}"
          
          WORKFLOW=""
          if [ "$COMMENT" = "run tests" ]; then
            WORKFLOW="pr-jobs" 
          elif [ "$COMMENT" = "make app" ]; then
            WORKFLOW="build-app"
          elif [ "$COMMENT" = "unit test" ]; then
            WORKFLOW="unit-test"
          fi
          
          if [ "$WORKFLOW" != "" ]; then
            BRANCH="${{ steps.pr-result.outputs.branch }}"
            HASH="${{ steps.pr-result.outputs.sha }}"
            APP_SLUG=${{ secrets.BITRISE_APP_SLUG }}
            BUILD_TRIGGER_TOKEN=${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
            echo "${BRANCH} ${HASH}"
            curl https://app.bitrise.io/app/$APP_SLUG/build/start.json --data '{"hook_info":{"type":"bitrise","build_trigger_token":"'${BUILD_TRIGGER_TOKEN}'"}, "build_params":{"branch":"'${BRANCH}'","workflow_id":"'${WORKFLOW}'","commit_hash":"'${HASH}'"},"triggered_by":"curl"}'
          else
            echo "Workflow not found"
          fi
