name: Bitrise-PR-comment

on: issue_comment
jobs:  
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
          echo "Comment on PR #${{ github.event.issue.pull_request }}"
          echo "Comment on PR #${{ github.event.issue.pull_request.comments }}"
          echo "Comment on PR #${{ github.event.issue.pull_request.review_comments }}"
          echo "Comment on PR #${{ github.event.issue.pull_request.html }}"
          echo "Comment on PR #${{ this }}"
    
