# Dumps the full GITHUB_CONTEXT, useful for debugging.
# Triggered by issuing a comment: `github_info`
name: Dump GitHub context

on: issue_comment

jobs:
  pr_commented:
    if: ${{ github.event_name == 'issue_comment' && github.event.comment.body == 'github_info' }}
    runs-on: ubuntu-latest
    steps:
      - id: dump-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "PR Number -> ${{ steps.dump-context.outputs.number }}"
          echo "Branch Name -> ${{ steps.dump-context.outputs.head.ref }}"
          echo "PR Title -> ${{ steps.dump-context.outputs.title }}"
          echo "Author -> ${{ steps.dump-context.outputs.user.login }}"
