# This is a basic workflow to help you get started with Actions

name: Welcome-PR

# Controls when the workflow will run
on: 
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 Hello @${{ github.actor }}, you can re-run Bitrise workflow using the following commands\n`run tests` to run `pr-jobs`\n`make app` to run `build-app`\n`unit test` to run `unit-test`"
            })
